### ISSUE TITLE
Batch logging of values

### ISSUE THREAD

**Issue by magnusja** [TeamHG-Memex/tensorboard_logger#14]
Hey there, what about batch logging with for instance numpy arrays?

**Comment by lopuhin** [comment]
Hey @magnusja , do you want to log numpy arrays as tensors (so each log entry is a tensor), or have scalars as log entries that are populated from numpy array? And what would batch logging mean in this context?

**Comment by magnusja** [comment]
So with batch logging I mean to log multiple values at once. I have all my values I would like to log in a numpy array, and now I am using a loop to log them. It would be nice to do that with one function call. (Not very critical, but maybe ncie to have :)

**Comment by lopuhin** [comment]
Thanks for explanation @magnusja !
Maybe my judgment is wrong here, but I feel like it should not be part of the library API, because it looks easy enough to accomplish outside and does not seem a common use.
