### ISSUE TITLE
can  it show train/eval summaries in one plot?

### ISSUE THREAD

**Issue by rgtjf** [TeamHG-Memex/tensorboard_logger#19]

**Comment by lopuhin** [comment]
@rgtjf that's a good question! Here is how it's done with vanilla tensorboard (initially I thought that it's not possible): https://github.com/tensorflow/tensorflow/issues/7089#issuecomment-295857875 - so it should be possible to achieve the same with tensorboard_logger

**Comment by rgtjf** [comment]
@lopuhin Great! Thanks a lot. :)

**Comment by rgtjf** [comment]
@lopuhin, I find another simple but efficient solutions!
```bash
tensorboard --logdir name1:/path/to/logs/1,name2:/path/to/logs/2
```

Ref:
https://github.com/tensorflow/tensorboard

**Comment by lopuhin** [comment]
@rgtjf wow, that's an awesome solution, thanks for sharing!
