### ISSUE TITLE
Plotting Precision Recall Curve

### ISSUE THREAD

**Issue by pyaf** [TeamHG-Memex/tensorboard_logger#23]
Hi, 
I'm training a object detection framework, at the end of each epoch I want to plot Precision Recall curve on tensorboard. As far as I can I have `log_value` function which takes one value (float/int) at a time and `log_histogram` takes a value (list/tuple) which can't be used to plot the PR curve. 
Is there any way I can plot PR curve using tensorboard_logger?

**Comment by lopuhin** [comment]
Hi @pyaf, do you know how to accomplish this with just tensorboard? Do you want to log how PR curve changes over the course of training, or plot a single PR curve?

**Comment by pyaf** [comment]
> do you know how to accomplish this with just tensorboard?
Nope
> Do you want to log how PR curve changes over the course of training, or plot a single PR curve?
I want to log how PR curve changes over the course of training.
